name: branch name

on:
    create:
    workflow_dispatch:

env:
    feature: ${{ ${GITHUB_REF#refs/heads/} }}

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - name: 'branch'
            run: echo ${{ env.feature }}
