name: branch name

on:
    create:
    workflow_dispatch:

env:
    feature: $GITHUB_REF_NAME

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - name: 'branch'
            run: echo ${{ env.feature }}
