name: branch name

on:
    create:
    workflow_dispatch:

env:
    feature: $GITHUB_REF_NAME

jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
          - name: 'branch'
            env:
                CYPRESS_GLEWEE_WEB: 'https://feature-${{ github.ref_name }}.glewee.io'
            run: \ 
                echo $CYPRESS_GLEWEE_WEB \
                echo $FEATURE
                echo ${{ env.feature }} 
