name: Github process
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - 'main'
    paths:
      - 'src/**'
      - 'types/**'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    if: ${{ github.event_name	== 'workflow_dispatch' || github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Create new branch
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git checkout -b update

      - name: Make changes and commit
        run: |
          echo $RANDOM > update.txt
          git add .
          git commit -m "Update package"
        
      - name: Create pull request and merge to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin update
          gh pr create -B main -H update --title 'Merge update into main' --body 'Created by Github action'
          gh pr merge --merge --auto update
